### ISSUE TITLE
Encountering NaN loss during reproduction

### ISSUE THREAD

**Issue by redleaf-kim** [reml-group/MUSIC-AVQA-R#1]
First of all, thank you for the great work.

During the reproducing your work, I encountered 'nan loss'.  During debugging, I found that NaN gradients repeatedly keep occuring between epochs 6 to 9. I am not sure what is causing this issue. I have not made any changes to your code. To resolve this error, I have tried reinitializing the layers, but the issue persists.

Could you please provide any insights or suggestions on how to fix this problem?
Thank you.

![nan gradient](https://github.com/reml-group/MUSIC-AVQA-R/assets/41847456/01005843-96c6-439d-9231-53ccdc7f68af)

**Comment by redleaf-kim** [comment]
```
python main.py
[2024-07-06 06:40:52,801]-[factory.py line:24]: Finish loading the train split. 
[2024-07-06 06:40:53,092]-[factory.py line:26]: Finish loading the val split. 
[2024-07-06 06:40:53,093]-[main.py line:11]:Code begin to run, model named [sens-0]. 
[2024-07-06 06:40:53,093]-[engine.py line:81]:Begin to train. 
[2024-07-06 06:40:53,094]-[engine.py line:85]:The number of trainable parameters is 117191336 
[2024-07-06 06:40:53,097]-[engine.py line:95]:Train epoch 1 begin 
[2024-07-06 06:40:54,438]-[engine.py line:78]:Epoch 1 complete [0%]     Loss: 3.709857 
[2024-07-06 06:41:25,455]-[engine.py line:78]:Epoch 1 complete [10%]    Loss: 2.799116 
[2024-07-06 06:41:56,752]-[engine.py line:78]:Epoch 1 complete [20%]    Loss: 1.711389 
[2024-07-06 06:42:28,170]-[engine.py line:78]:Epoch 1 complete [30%]    Loss: 1.510960 
[2024-07-06 06:42:59,614]-[engine.py line:78]:Epoch 1 complete [40%]    Loss: 1.390983 
[2024-07-06 06:43:31,148]-[engine.py line:78]:Epoch 1 complete [50%]    Loss: 1.554311 
[2024-07-06 06:44:02,712]-[engine.py line:78]:Epoch 1 complete [60%]    Loss: 1.583764 
[2024-07-06 06:44:34,306]-[engine.py line:78]:Epoch 1 complete [70%]    Loss: 1.141079 
[2024-07-06 06:45:05,900]-[engine.py line:78]:Epoch 1 complete [80%]    Loss: 1.516035 
[2024-07-06 06:45:37,519]-[engine.py line:78]:Epoch 1 complete [90%]    Loss: 1.181653 
/root/workspace/AVQA/MUSIC-AVQA-R/avqa_r/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:152: UserWarning: The epoch parameter in `schedule
r.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.                                                                     warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
[2024-07-06 06:46:23,746]-[engine.py line:107]:Train epoch 1 end, val get best acc 54.62% 
[2024-07-06 06:46:24,374]-[engine.py line:95]:Train epoch 2 begin 
[2024-07-06 06:46:25,733]-[engine.py line:78]:Epoch 2 complete [0%]     Loss: 1.320764 
[2024-07-06 06:46:57,300]-[engine.py line:78]:Epoch 2 complete [10%]    Loss: 1.060691 
[2024-07-06 06:47:28,868]-[engine.py line:78]:Epoch 2 complete [20%]    Loss: 1.222175 
[2024-07-06 06:48:00,498]-[engine.py line:78]:Epoch 2 complete [30%]    Loss: 1.049172 
[2024-07-06 06:48:32,077]-[engine.py line:78]:Epoch 2 complete [40%]    Loss: 1.079505 
[2024-07-06 06:49:03,657]-[engine.py line:78]:Epoch 2 complete [50%]    Loss: 1.121318 
[2024-07-06 06:49:35,260]-[engine.py line:78]:Epoch 2 complete [60%]    Loss: 0.853240 
[2024-07-06 06:50:06,867]-[engine.py line:78]:Epoch 2 complete [70%]    Loss: 0.949944 
[2024-07-06 06:50:38,471]-[engine.py line:78]:Epoch 2 complete [80%]    Loss: 0.891505 
[2024-07-06 06:51:10,071]-[engine.py line:78]:Epoch 2 complete [90%]    Loss: 1.011660 
[2024-07-06 06:51:56,100]-[engine.py line:107]:Train epoch 2 end, val get best acc 63.81% 
[2024-07-06 06:51:56,709]-[engine.py line:95]:Train epoch 3 begin 
[2024-07-06 06:51:57,814]-[engine.py line:78]:Epoch 3 complete [0%]     Loss: 0.912425 
[2024-07-06 06:52:29,388]-[engine.py line:78]:Epoch 3 complete [10%]    Loss: 0.997927 
[2024-07-06 06:53:00,967]-[engine.py line:78]:Epoch 3 complete [20%]    Loss: 0.813246 
[2024-07-06 06:53:32,596]-[engine.py line:78]:Epoch 3 complete [30%]    Loss: 1.052595 
[2024-07-06 06:54:04,163]-[engine.py line:78]:Epoch 3 complete [40%]    Loss: 0.742842 
[2024-07-06 06:54:35,735]-[engine.py line:78]:Epoch 3 complete [50%]    Loss: 1.043558 
[2024-07-06 06:55:07,304]-[engine.py line:78]:Epoch 3 complete [60%]    Loss: 0.967692 
[2024-07-06 06:55:38,874]-[engine.py line:78]:Epoch 3 complete [70%]    Loss: 1.148149 
[2024-07-06 06:56:10,448]-[engine.py line:78]:Epoch 3 complete [80%]    Loss: 0.725714 
[2024-07-06 06:56:42,023]-[engine.py line:78]:Epoch 3 complete [90%]    Loss: 0.877223 
[2024-07-06 06:57:28,101]-[engine.py line:107]:Train epoch 3 end, val get best acc 67.03% 
[2024-07-06 06:57:28,709]-[engine.py line:95]:Train epoch 4 begin 
[2024-07-06 06:57:29,820]-[engine.py line:78]:Epoch 4 complete [0%]     Loss: 0.704021 
[2024-07-06 06:58:01,400]-[engine.py line:78]:Epoch 4 complete [10%]    Loss: 0.857246 
[2024-07-06 06:58:32,966]-[engine.py line:78]:Epoch 4 complete [20%]    Loss: 0.766861 
[2024-07-06 06:59:04,538]-[engine.py line:78]:Epoch 4 complete [30%]    Loss: 0.734813 
[2024-07-06 06:59:36,119]-[engine.py line:78]:Epoch 4 complete [40%]    Loss: 0.740789 
[2024-07-06 07:00:07,741]-[engine.py line:78]:Epoch 4 complete [50%]    Loss: 0.554101 
[2024-07-06 07:00:39,304]-[engine.py line:78]:Epoch 4 complete [60%]    Loss: 0.755112 
[2024-07-06 07:01:10,877]-[engine.py line:78]:Epoch 4 complete [70%]    Loss: 1.014579 
[2024-07-06 07:01:42,455]-[engine.py line:78]:Epoch 4 complete [80%]    Loss: 0.925262 
[2024-07-06 07:02:14,026]-[engine.py line:78]:Epoch 4 complete [90%]    Loss: 0.819458 
[2024-07-06 07:03:00,031]-[engine.py line:107]:Train epoch 4 end, val get best acc 68.24% 
[2024-07-06 07:03:00,640]-[engine.py line:95]:Train epoch 5 begin 
[2024-07-06 07:03:01,693]-[engine.py line:78]:Epoch 5 complete [0%]     Loss: 0.673902 
[2024-07-06 07:03:33,249]-[engine.py line:78]:Epoch 5 complete [10%]    Loss: 0.550310 
[2024-07-06 07:04:04,816]-[engine.py line:78]:Epoch 5 complete [20%]    Loss: 0.655307 
[2024-07-06 07:04:36,394]-[engine.py line:78]:Epoch 5 complete [30%]    Loss: 0.594048 
[2024-07-06 07:05:07,965]-[engine.py line:78]:Epoch 5 complete [40%]    Loss: 0.713231 
[2024-07-06 07:05:39,607]-[engine.py line:78]:Epoch 5 complete [50%]    Loss: 0.798784 
[2024-07-06 07:06:11,184]-[engine.py line:78]:Epoch 5 complete [60%]    Loss: 0.552691 
[2024-07-06 07:06:42,753]-[engine.py line:78]:Epoch 5 complete [70%]    Loss: 0.657422 
[2024-07-06 07:07:14,311]-[engine.py line:78]:Epoch 5 complete [80%]    Loss: 0.641232 
[2024-07-06 07:07:45,872]-[engine.py line:78]:Epoch 5 complete [90%]    Loss: 0.670481 
[2024-07-06 07:08:31,890]-[engine.py line:107]:Train epoch 5 end, val get best acc 70.01% 
[2024-07-06 07:08:32,494]-[engine.py line:95]:Train epoch 6 begin 
[2024-07-06 07:08:33,579]-[engine.py line:78]:Epoch 6 complete [0%]     Loss: 0.800303 
[2024-07-06 07:09:05,139]-[engine.py line:78]:Epoch 6 complete [10%]    Loss: 0.473028 
[2024-07-06 07:09:36,710]-[engine.py line:78]:Epoch 6 complete [20%]    Loss: 0.720272 
[2024-07-06 07:10:08,288]-[engine.py line:78]:Epoch 6 complete [30%]    Loss: 0.529923 
[2024-07-06 07:10:39,873]-[engine.py line:78]:Epoch 6 complete [40%]    Loss: 0.532142 
[2024-07-06 07:11:11,454]-[engine.py line:78]:Epoch 6 complete [50%]    Loss: 0.750625 
[2024-07-06 07:11:43,082]-[engine.py line:78]:Epoch 6 complete [60%]    Loss: 0.588099 
[2024-07-06 07:12:14,650]-[engine.py line:78]:Epoch 6 complete [70%]    Loss: 0.647283 
[2024-07-06 07:12:46,236]-[engine.py line:78]:Epoch 6 complete [80%]    Loss: 0.599582 
[2024-07-06 07:13:17,818]-[engine.py line:78]:Epoch 6 complete [90%]    Loss: 0.496943 
[2024-07-06 07:14:04,079]-[engine.py line:107]:Train epoch 6 end, val get best acc 70.51% 
[2024-07-06 07:14:04,689]-[engine.py line:95]:Train epoch 7 begin 
/root/workspace/AVQA/MUSIC-AVQA-R/avqa_r/lib/python3.9/site-packages/torch/nn/modules/module.py:1554: UserWarning: For backward hooks to be called,
 module output should be a Tensor or a tuple of Tensors but received <class 'transformers.modeling_outputs.BaseModelOutput'>                         warnings.warn("For backward hooks to be called,"
/root/workspace/AVQA/MUSIC-AVQA-R/avqa_r/lib/python3.9/site-packages/torch/nn/modules/module.py:1554: UserWarning: For backward hooks to be called,
 module output should be a Tensor or a tuple of Tensors but received <class 'transformers.modeling_outputs.BaseModelOutputWithPooling'>              warnings.warn("For backward hooks to be called,"
/root/workspace/AVQA/MUSIC-AVQA-R/avqa_r/lib/python3.9/site-packages/torch/nn/modules/module.py:1554: UserWarning: For backward hooks to be called,
 module output should be a Tensor or a tuple of Tensors but received <class 'dict'>                                                                  warnings.warn("For backward hooks to be called,"
[2024-07-06 07:14:06,142]-[engine.py line:78]:Epoch 7 complete [0%]     Loss: 0.714831 
[2024-07-06 07:14:45,333]-[engine.py line:78]:Epoch 7 complete [10%]    Loss: 0.437472 
[2024-07-06 07:15:24,543]-[engine.py line:78]:Epoch 7 complete [20%]    Loss: 0.430946 
[2024-07-06 07:16:03,790]-[engine.py line:78]:Epoch 7 complete [30%]    Loss: 0.630294 
NaN gradient detected in output of Linear(in_features=768, out_features=42, bias=True) at index 0
Traceback (most recent call last):
  File "/root/workspace/AVQA/MUSIC-AVQA-R/main.py", line 15, in <module>
    engine.train()
  File "/root/workspace/AVQA/MUSIC-AVQA-R/engine.py", line 103, in train
    self.train_one_epoch(epoch, train_data_loader, optimizer, criterion)
  File "/root/workspace/AVQA/MUSIC-AVQA-R/engine.py", line 72, in train_one_epoch
    loss.backward()
  File "/root/workspace/AVQA/MUSIC-AVQA-R/avqa_r/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/workspace/AVQA/MUSIC-AVQA-R/avqa_r/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/workspace/AVQA/MUSIC-AVQA-R/avqa_r/lib/python3.9/site-packages/torch/utils/hooks.py", line 137, in hook
    out = hook(self.module, res, self.grad_outputs)
  File "/root/workspace/AVQA/MUSIC-AVQA-R/engine.py", line 34, in gradient_hook
    raise RuntimeError("NaN gradient detected in output")
RuntimeError: NaN gradient detected in output

```

**Comment by dr-majie** [comment]
Hi, I am very sorry for replying to you late. Do you address this issue?  Is the virtual environment you installed the same as the one we provided?
